import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Navbar, Nav, Container, NavDropdown} from 'react-bootstrap'
import NavBar from './Components/navbar'

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>

function Home({category}) {
  console.log(category)
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Tv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      <NavBar />

      </Head>

      <main className={styles.main}>


        <h3 className={styles.title}>
        1ST EDITION SHOW ON ADOA TV
        </h3>

        <p className={styles.description}>
          Choose a Movie title to vote
        </p>

        <div className={styles.grid}>
          {category.map((category) =>
         
            <a href={category.id} className={styles.card}>
            <h2>{category.category} &rarr;</h2>
            <p>Click here to vote for your favorite contestant.</p>
          </a>
      
            )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://cozytechsolutionsgh.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Cozytechsolutions
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;

export async function getServerSideProps() {
  const category = await fetch("http://localhost:8000/api/categories")
  const categoryData = await category.json();


  return {
    props: { category: categoryData, },
  };
}

