# Generated by Django 4.0.2 on 2022-02-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='LEADING ROLE ACTOR', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contestants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contestants',
            },
        ),
        migrations.CreateModel(
            name='MovieTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination_code', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(default='LEADING ROLE ACTOR', on_delete=django.db.models.deletion.CASCADE, to='MainApp.category')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.contestants')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.movietitle')),
            ],
            options={
                'verbose_name_plural': 'Nominations',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('category', models.ForeignKey(default='LEADING ROLE ACTOR', on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='MainApp.nominations')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_name', to='MainApp.nominations')),
                ('nomination_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='MainApp.nominations')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_category_title', to='MainApp.nominations')),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
