# Generated by Django 4.0.2 on 2022-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_category_category_alter_nominations_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominations',
            name='vote_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
