
import {Navbar, Nav, Container} from 'react-bootstrap'


function NavBar() {
  return (
    <div>
        <title>Next Tv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <Navbar collapseOnSelect expand="lg" bg="dark" variant="dark">
            <Container>
                <Navbar.Brand href="#home">NEXT TV SERIES ICON</Navbar.Brand>

                <Nav>
                    <Nav.Link href="#features">Vote</Nav.Link>
                    <Nav.Link href="#pricing">Movies</Nav.Link>
                </Nav> 
                
            </Container>
        </Navbar>

    </div>
  )
}

export default NavBar;
